declare module "@editorjs/header"
declare module "@editorjs/list"
declare module "@editorjs/checklist"
declare module "@editorjs/embed"
declare module "@editorjs/quote"
declare module "@editorjs/raw"
declare module "@editorjs/table"
declare module "@editorjs/marker"
declare module "@editorjs/code"
// declare module "@editorjs/editorjs"